### ISSUE TITLE
CUDA hasn't enough memory, am unable to discover the method for utilizing CPU alone

### ISSUE THREAD

**Issue by winterfate** [CorentinJ/Real-Time-Voice-Cloning#423]
Good day.
    I have installed everything perfectly(or so it would seem). I am able to synthesize and vocode once, and occasionally twice, before being notified that CUDA has run out of memory, while I have a total of 4 GB in my GPU.  I have discovered a statement by @blue-fish that we are now able to utilize the CPU, no longer being forced to use the GPU. Is this true? If so, how is this achieved? I am relatively new to this, but have been learning more and more through my programming and tech journey. This is all incredibly fascinating, but the issue I am dealing with does indeed escape the scope of my comprehension as of yet. Absolutely ecstatic about @CorentinJ 's work. Supremely excited, even. Imagine Tony Stark reading me a bedtime story.

**Comment by blue-fish** [comment]
@winterfate I messed up in #406 and removed CPU mode not realizing you would have a use case here with a low-memory GPU. Thanks for reporting this.

### Option 1 - Add CPU mode back into demo_cli.py using my fork
You can clone the `423_add_cpu_mode` branch of my fork:
```
git clone --depth 1 -b 423_add_cpu_mode https://github.com/blue-fish/Real-Time-Voice-Cloning
```
### Option 2: Add CPU mode to demo_cli.py yourself
Or modify your demo_cli.py for [line 35](https://github.com/blue-fish/Real-Time-Voice-Cloning/blob/614c52601f2f33c56c9d1c27e227796a83802fa8/demo_cli.py#L35) and [line 43](https://github.com/blue-fish/Real-Time-Voice-Cloning/blob/614c52601f2f33c56c9d1c27e227796a83802fa8/demo_cli.py#L43). I don't have an immediate fix to force the toolbox into CPU mode when a GPU is present. That will be a larger change.

### Option 3: Use virtual environment to force torch into CPU-only mode
A workaround is to use a virtual environment and install a CPU-only torch so `torch.cuda.is_available()` will evaluate to False. This will allow you to use both demo_cli.py and demo_toolbox.py in CPU mode.

**Comment by winterfate** [comment]
@blue-fish forgive my ignorance, but I have used the code provided by the Option 1, and I seem to still be running on GPU. Woudl you be willing to provide any step-by-step instructions? I thought I had Github Desktop and the CMD figured out, but it would appear I am wrong.

**Comment by winterfate** [comment]
@blue-fish I suppose I need to know how to commit that download to my local master, but I've absolutely no idea how to do so and Google is giving me bollocks.

**Comment by winterfate** [comment]
@blue-fish absolutely f**k me. I thought I had it fixed after being able to synthesize and vocode 3 times in a row(a new record for me), but then it gave me the same error. Shaking my head. Damn. So close.

**Comment by blue-fish** [comment]
@winterfate Can you install a CPU-only torch in a virtual environment? Basically what I said in option 3. I think that will be best. Let me know how it goes.

**Comment by winterfate** [comment]
> @winterfate Can you install a CPU-only torch in a virtual environment? Basically what I said in option 3. I think that will be best. Let me know how it goes.

@blue-fish I thought I installed it with a virtual environment, however, I did not. I installed into my real repo, I suppose. Either way, it works. It works at .25(or 1/4) real-time speed, and only utilizes about half my cpu capacity for some reason, but it does work. So now, I suppose- what do I need to do to convince it to use, say, 90% of my CPU?

**Comment by blue-fish** [comment]
@winterfate I have a bunch of stuff for you to try:

1. There is a "--low_mem" flag which which frees the GPU memory used by the synthesizer after each use. This may be a better solution to your problem.
2. If the goal is to use CPU, I found an easier way to cause torch.cuda.is_available() to evaluate to False, by setting the `CUDA_VISIBLE_DEVICES` environment variable to "" within Python. It even works for demo_toolbox.py (and we could also extend it to the training scripts which now work on CPU). This is committed to my fork and I would appreciate it if you could let me know if it works (so we can get it merged upstream). `python demo_toolbox.py --cpu`

> @blue-fish I suppose I need to know how to commit that download to my local master, but I've absolutely no idea how to do so and Google is giving me bollocks.

If you want to try 2, this is the command to merge it with your local master:
```
git pull https://github.com/blue-fish/Real-Time-Voice-Cloning 423_add_cpu_mode
```

Regarding the partial CPU utilization, that is also my experience and I do not know how to increase it. Multiprocessing for vocoder is not a linear speedup because of the overhead, so you are not really missing much in terms of speed.

**Comment by winterfate** [comment]
@blue-fish I am very happy about the --low_mem. God bless you. Out of curiosity, what are the benefits of having high memory and not needing low_mem? Why is low_mem not default?

I tried number 2 for you. It gives:

```
C:\Users\Shawn\Documents\GitHub\Real-Time-Voice-Cloning>python demo_toolbox.py --cpu
2020-07-13 17:43:28.893897: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    low_mem:          False
    cpu:              True

Traceback (most recent call last):
  File "demo_toolbox.py", line 35, in <module>
    os.environ["CUDA_VISIBLE_DEVICES"]=""
NameError: name 'os' is not defined
```

**Comment by winterfate** [comment]
@blue-fish Another question I meant to ask you- what do I need to do to teach the AI pronunciation? Perhaps it could view subtitles while processing the individual audio clips?

**Comment by blue-fish** [comment]
> Out of curiosity, what are the benefits of having high memory and not needing low_mem? Why is low_mem not default?

Good question. The intended audience for this repo is researchers who will have access to higher-end GPUs with lots of memory. Though we might revisit that assumption. Thank you for the suggestion to make low_mem default, it will be considered. If more people report the same issue we might go ahead and implement it.

> I tried number 2 for you. It gives: `NameError: name 'os' is not defined`

Much appreciated. Can you please pull the latest and try again? I missed an `import os` at the top.

> @blue-fish Another question I meant to ask you- what do I need to do to teach the AI pronunciation?

In [synthesizer/utils/cleaners.py](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/synthesizer/utils/cleaners.py) you can make a text cleaner that preprocesses your input text. For example, intentionally misspelling words to encourage the synthesizer to the desired pronunciation. This could be done when you input text as well.

It is also possible to fine-tune the pretrained models but that is likely a lot more effort that you are willing to put into it. You likely need a GPU with more memory as well. If you are thinking about an accent, that has been requested several times, but no one has spent the time to train a model and share it with the community.

**Comment by winterfate** [comment]
@blue-fish You have been helpful beyond comprehension, and have been instrumental in the enhancement of both my AI education and passion. From the entire surface of my heart, including the aorta, as opposed to just the bottom of my heart- thank you.
