### ISSUE TITLE
Pytorch not working on RTX 30X0 nvidia GPU (CUDA capability sm_86)

### ISSUE THREAD

**Issue by rallandr** [CorentinJ/Real-Time-Voice-Cloning#584]
Hi everyone, 

I just bought a Nvidia RTX 3070 and I was thrilled to do some training with it but it appears Pytorch doesn't work with my new GPU...

Here is the message I get, and there is no help on the pytorch webpage.

"
GeForce RTX 3070 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the GeForce RTX 3070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
"

Is there anyone out here using RTX 30 series GPU that could help me?

Thanks a lot

**Comment by blue-fish** [comment]
Please open an issue in the pytorch repo, they will be able to help you a lot better than we can. https://github.com/pytorch/pytorch/

**Comment by rallandr** [comment]
I solved it by installing Pytorch 1.8 and CUDA 11, but now I have several errors because it's meant to run with Pytorch 1.6 and CUDA 10....
