### ISSUE TITLE
Can't synthesize and vocode (CUDA out of memory)

### ISSUE THREAD

**Issue by Bunkowaty** [CorentinJ/Real-Time-Voice-Cloning#809]
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 939.96 MiB already allocated; 0 bytes free; 962.00 MiB reserved in total by PyTorch) This error occurs when i'm trying synthesize and vocode.

**Comment by babysor** [comment]
You might need to use a better GPU. I got the same error using my 940MX after 1min training, but I ran finely with 2060GTX after hours.

**Comment by stedylan** [comment]
> RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 939.96 MiB already allocated; 0 bytes free; 962.00 MiB reserved in total by PyTorch) This error occurs when i'm trying synthesize and vocode.

you can try to decrease the **synthesis_batch_size** in synthesizer\hparams.py, my case is 2, and it works

**Comment by iloveflag** [comment]
> > RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 939.96 MiB already allocated; 0 bytes free; 962.00 MiB reserved in total by PyTorch) This error occurs when i'm trying synthesize and vocode.
> 
> you can try to decrease the **synthesis_batch_size** in synthesizer\hparams.py, my case is 2, and it works

also same error using my 940MX，it doesn't work

**Comment by blue-fish** [comment]
You can also run demo_cli.py and demo_toolbox.py with the `--cpu` option to bypass the GPU's limited memory.
