### ISSUE TITLE
Pytorch cannot allocate enough memory

### ISSUE THREAD

**Issue by craftpag** [CorentinJ/Real-Time-Voice-Cloning#913]
Hello!

I am trying to run encoder_train.py
I have preprocessed Train_other_500, but when I try to start encoder_train.py I get this message
` CUDA out of memory. Tried to allocate 4.98 GiB (GPU 0; 8.00 GiB total capacity; 1.64 GiB already allocated; 4.51 GiB free; 1.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

if I have read it correctly, i most add/change `max_split_size_mb = <value>` to one of the codes. I have tried to search around, and everyone has a solution but none of them says where to change the code.

Where do i add/change the code, to add `max_split_size_mb = <value>`?

this may be a stupid question, but I am lost. 

Specs:
Windows 11 PRO 21H2
RTX3070 
AMD Rysen 7 5800x
32Gb DDR4 3200MH/z
Pytorch 1.10, CUDA 11.3
Python 3.7.9

**Comment by sveneschlbeck** [comment]
@craftpag This is not a parameter to be found in the code here but a PyTorch command that (if I'm not wrong) needs to be set as an environment variable.
Try setting ``PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:<cache in mb here>``.

Doc Quote: "``max_split_size_mb`` prevents the allocator from splitting blocks larger than this size (in MB). This can help prevent fragmentation and may allow some borderline workloads to complete without running out of memory."

Checkout this link to see the full documentation for PyTorch's memory management:
https://pytorch.org/docs/stable/notes/cuda.html

**Comment by craftpag** [comment]
Hello
Thank you for replying @sveneschlbeck

I have tried to add those environment variables, with no luck.
I have tried to add it in different ways, but I still get the same error.
Do you think it can be other solutions out there?

**Comment by sveneschlbeck** [comment]
@craftpag

There's a couple of things remaining until I am out of answers, too:

**1. Are you running any other scripts/games/programs that might be taking up GPU memory? If so, do the following:**

Type ``nvidia-smi`` into the terminal and find the ``PID`` of the process using most GPU memory (apart from PyTorch of course), then kill it gy typing ``taskkill /F /PID <your PID here>``

2. Try to reduce memory-intensive (hyper)parameters, e.g. train/test size, batch size, etc.

3. Run

```python
import torch
torch.cuda.empty_cache()
```

My guess is that it's the ``batch_size`` since that is where you specify how much data is loaded into the memory at once. See #914 to get an idea on where you can decrease the batch size. I'd do it file after file to see where the error is caused. Alternatively, you can change it in all files at once. But keep in mind that a lower batch size results in a longer training/testing duration...

**Comment by craftpag** [comment]
yes @sveneschlbeck 

Tried the Nvidia-smi, but that didn't fix it.
i have imported the `torch.Cuda.empty_cache()`
to `train.py` but that didn't sole it ether.

the problem was in `params_model.py`
The values are now.
`## Model parameters`
`model_hidden_size = 128`
`model_embedding_size = 128`
`model_num_layers = 3`

`## Training parameters`
`learning_rate_init = 1e-4`
`speakers_per_batch = 128`
`utterances_per_speaker = 5`

They were much higher 
If you have some improvements say what I should change, but this "Works"

Thank you!

**Comment by sveneschlbeck** [comment]
@craftpag Your batch and embedding sizes look reasonable to me...glad it worked :)

**Comment by gauraviiita** [comment]
I faced the same problem and resolved it by degrading the PyTorch version from 1.10.1 to 1.8.1 with code 11.3.
In my case, I am using GPU RTX 3060, which works only with Cuda version 11.3 or above, and when I installed Cuda 11.3, it came with PyTorch 1.10.1. So I degraded the PyTorch version, and now it is working fine.

$ **pip3 install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html**

2- You can check by reducing train batch size also.

**Comment by gayanechilingar** [comment]
I had the same error and I used **torch.no_grad()** [https://pytorch.org/docs/stable/generated/torch.no_grad.html].

**Comment by DarkSynx** [comment]
Whether it's Angular or Python, it's always a mess, there's EVER nothing that works correctly straight away, it's always projects within projects, endless waste of time, we spend 99% of our time patching what should work natively.
I don't really understand that we develop AI software without even fucking AI in solving 99% of this kind of problem! we want it to work, not spend our lives imagining that one day it will work.

**Comment by abderhasan** [comment]
> I faced the same problem and resolved it by degrading the PyTorch version from 1.10.1 to 1.8.1 with code 11.3. In my case, I am using GPU RTX 3060, which works only with Cuda version 11.3 or above, and when I installed Cuda 11.3, it came with PyTorch 1.10.1. So I degraded the PyTorch version, and now it is working fine.
> 
> $ **pip3 install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html**
> 
> 2- You can check by reducing train batch size also.

Yes, reducing the batch size worked with me many times :-)

**Comment by YJonmo** [comment]
I had a similar issue even with batch size 1:
![image](https://user-images.githubusercontent.com/12040950/210911539-ca30c154-91d2-4a06-985f-a93307c3279e.png)


I change the number of workers in the dataloader from 4 to 2 and it was solved.

**Comment by tworods** [comment]
> @craftpagЭто не параметр, который можно найти в коде здесь, команда PyTorch, которую необходимо установить как переменную среду. Попробуйте установить `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:<cache in mb here>`.
> 
> Цитата из документа: « `max_split_size_mb`примерное разбиение распределителем блоков большего размера (в МБ). Это может помочь взломать фрагментацию и может быть реализовано без нехватки памяти».
> 
> Перейдите по этой ссылке, чтобы просмотреть полную документацию по управлению памятью PyTorch: [https://pytorch.org/docs/stable/notes/cuda.html.](https://pytorch.org/docs/stable/notes/cuda.html)

Извините, Читаю ваши посты и не понимаю куда вставить, что скачать. 
Вот это что файл какой то ? PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:<cache in mb here>
Или где то его прописывать нужно? 
Пишите: я вписал в переменную среду( что это?)) Я вижу вы тут программисты друг друга с полу слова понимаете))
Извините, но я ноль. Досмотрел все видосы xpuct . И на последних видосах моя память заполнена 14 гигами из 16 pythonom  ))
Ничего своего не скачивал, по раз 10 перепроверял что качаю и что советует блогер скачать
Походу я такой дурачек, что мне легче еще 16 гигов памяти купить))

**Comment by craftpag** [comment]
What I did to fix it was in the `params_model.py` The file is in the `Real-Time-Voice-Cloning-master\encoder\params_model.py`
I change the values from:

`## Model parameters`
`model_hidden_size = 256`
`model_embedding_size = 256`
`model_num_layers = 3`

to

`## Model parameters`
`model_hidden_size = 128`
`model_embedding_size = 128`
`model_num_layers = 3`

and that fixed the problem for me. 
It is not too little memory problem, because you will get the same error with a 3090.

Are you able to run `demo_toolbox.py` if not what is the error?

**Comment by Aloento** [comment]
`CUDA out of memory. Tried to allocate 9.90 GiB (GPU 0; 16.00 GiB total capacity; 2.44 GiB already allocated; 10.04 GiB free; 4.05 GiB reserved in total by PyTorch) `

**Comment by shaharMazia** [comment]
I get as well:
`RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 10.76 GiB total capacity; 4.07 GiB already allocated; 646.44 MiB free; 8.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I am not sure what values to try to set in `PYTORCH_CUDA_ALLOC_CONF`

**Comment by B-Mirzababaei** [comment]
If using Transformers, just add _auto_find_batch_size=True_ in TrainingArguments

**Comment by 1318980306** [comment]
For PYTORCH_CUDA_ALLOC_CONF, Is it more values we set, the more available memory we got? or less. Sorry, I am not a coder.

**Comment by Michael-Fletcher** [comment]
I don't know if this is "The right way" or even the working way, but this is what I did. It seems to have helped but it's a little intermittent.

I downloaded NVidia's CUDA-MEMCHECK utility from their developer website.  After installing the file which was 3GB, everything was like speed central. I'm rendering 8k images in seconds now.  I suspect this issue is mainly a Windows one. I didn't actually do anything with the files it installed. 

I also added this to my python at the start
```
torch.cuda.init()  # Initialize CUDA
torch.cuda.empty_cache()  # Clear cache if needed
torch.cuda.reset_peak_memory_stats()  # Reset peak memory stats - Potentially not wise to add this.
```
Then this at the end. 
```
torch.cuda.empty_cache()
```
